In [1]:
import pandas as pd 
import numpy as np 

df = pd.read_excel('dados/economi.xlsx')

display(df)
display(df.head())
display(list(df.columns)) #descreve o nome das colunas em uma lista 
display(df.info())
display(df.describe())

,Trimestre,Ano,M - oferta monetaria,V - velocidade,Y - produto real,P - nivel de precos
0,2020T1,2020,103.665,0.98913,101.453,NaN
1,2020T2,2020,107.297,0.97758,100.382,NaN
2,2020T3,2020,111.334,0.95334,100.716,NaN
3,2020T4,2020,115.307,0.94183,101.323,NaN
4,2021T1,2021,117.442,0.94028,102.656,NaN
5,2021T2,2021,119.981,0.94031,104.194,NaN
6,2021T3,2021,121.833,0.94807,105.601,NaN
7,2021T4,2021,123.789,0.95386,106.626,NaN
8,2022T1,2022,126.473,0.95405,107.637,NaN
9,2022T2,2022,129.152,0.96242,108.359,NaN
10,2022T3,2022,131.163,0.97666,109.301,NaN
11,2022T4,2022,134.045,0.97552,110.694,NaN
12,2023T1,2023,136.819,0.98957,111.050,NaN
13,2023T2,2023,139.228,0.98663,112.385,NaN
14,2023T3,2023,141.662,1.00162,113.228,NaN
15,2023T4,2023,144.555,1.01500,113.892,NaN
16,2024T1,2024,147.286,1.03037,114.954,NaN
17,2024T2,2024,149.867,1.03176,116.384,NaN
18,2024T3,2024,152.317,1.04009,117.509,NaN
19,2024T4,2024,155.192,1.03863,118.790,NaN
20,2025T1,2025,158.515,1.04110,119.619,NaN
21,2025T2,2025,161.902,1.04897,120.370,NaN
22,2025T3,2025,164.341,1.06058,121.233,NaN
23,2025T4,2025,167.344,1.06212,122.518,NaN

,Trimestre,Ano,M - oferta monetaria,V - velocidade,Y - produto real,P - nivel de precos
0,2020T1,2020,103.665,0.98913,101.453,NaN
1,2020T2,2020,107.297,0.97758,100.382,NaN
2,2020T3,2020,111.334,0.95334,100.716,NaN
3,2020T4,2020,115.307,0.94183,101.323,NaN
4,2021T1,2021,117.442,0.94028,102.656,NaN

['Trimestre',
 'Ano',
 'M - oferta monetaria',
 'V - velocidade',
 'Y - produto real',
 'P - nivel de precos']

<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Trimestre             24 non-null     str
 1   Ano                   24 non-null     int64
 2   M - oferta monetaria  24 non-null     float64
 3   V - velocidade        24 non-null     float64
 4   Y - produto real      24 non-null     float64
 5   P - nivel de precos   0 non-null      float64
dtypes: float64(4), int64(1), str(1)
memory usage: 1.4 KB

None

,Ano,M - oferta monetaria,V - velocidade,Y - produto real,P - nivel de precos
count,24.000000,24.000000,24.000000,24.00000,0.0
mean,2022.500000,135.854542,0.994145,110.86975,NaN
std,1.744557,18.714439,0.041254,7.07340,NaN
min,2020.000000,103.665000,0.940280,100.38200,NaN
25%,2021.000000,121.370000,0.954002,105.24925,NaN
50%,2022.500000,135.432000,0.987880,110.87200,NaN
75%,2024.000000,150.479500,1.033478,116.66525,NaN
max,2025.000000,167.344000,1.062120,122.51800,NaN

In [2]:
#seleção de colunas
display(df[['Ano', 'M - oferta monetaria']].head())

# tipos de dados
df['Ano'] = pd.to_datetime(df['Ano'], format='%Y')

display(df.info())


#Calculo de matemática entre colunas
df['P - nivel de precos'] = df['M - oferta monetaria'] * df['V - velocidade'] / df['Y - produto real']

display(df.head())

    Ano  M - oferta monetaria
0  2020               103.665
1  2020               107.297
2  2020               111.334
3  2020               115.307
4  2021               117.442

<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Trimestre             24 non-null     str
 1   Ano                   24 non-null     datetime64[us]
 2   M - oferta monetaria  24 non-null     float64
 3   V - velocidade        24 non-null     float64
 4   Y - produto real      24 non-null     float64
 5   P - nivel de precos   0 non-null      float64
dtypes: datetime64[us](1), float64(4), str(1)
memory usage: 1.4 KB

None

,Trimestre,Ano,M - oferta monetaria,V - velocidade,Y - produto real,P - nivel de precos
0,2020T1,2020-01-01,103.665,0.98913,101.453,1.010696
1,2020T2,2020-01-01,107.297,0.97758,100.382,1.044922
2,2020T3,2020-01-01,111.334,0.95334,100.716,1.053846
3,2020T4,2020-01-01,115.307,0.94183,101.323,1.071816
4,2021T1,2021-01-01,117.442,0.94028,102.656,1.075713

In [ ]:

# criar nova coluna

#calculo quantidade de moeda

df['Taxa de crescimento - M'] = df['M - oferta monetaria'].pct_change() * 100

#diferenca_m = df['Taxa de crescimento - M'] / 100

df['Media de crescimento - M'] = df['Taxa de crescimento - M'].mean() # média

#calculo velocidade de circulação
df['Taxa de crescimento - V'] = df['V - velocidade'].pct_change() * 100

# diferenca_v = df['Taxa de crescimento - V'] / 100

df['Media de crescimento - V'] = df['Taxa de crescimento - V'].mean() # média

#calculo produto

df['Taxa de crescimento - Y'] = df['Y - produto real'].pct_change() * 100



# diferenca_y = df['Taxa de crescimento - Y'] / 100

df['Media de crescimento - Y'] = df['Taxa de crescimento - Y'].mean() # média

#calculo preco

df['Taxa de crescimento - P'] = df['P - nivel de precos'].pct_change() * 100

#diferenca_p = df['Taxa de crescimento - P'] / 100

df['Media de crescimento - P'] = df['Taxa de crescimento - P'].mean() # média




# diferença  p= m + v - y

df['Inflacao aproximada'] = df['Taxa de crescimento - M'] + df['Taxa de crescimento - V'] - df['Taxa de crescimento - Y']

# df['Diferenca - P'] = np.where(df['P - real']==df['P - nivel de precos'], 0 , df['P - real']-df['P - nivel de precos'] ,  )

df['Erro aproximacao'] = df['Taxa de crescimento - P'] - df['Inflacao aproximada']

display(df.head())

df.info()
list(df.columns)

,Trimestre,Ano,M - oferta monetaria,V - velocidade,Y - produto real,P - nivel de precos,Taxa de crescimento - M,Media de crescimento - M,Taxa de crescimento - V,Media de crescimento - V,Taxa de crescimento - Y,Media de crescimento - Y,Taxa de crescimento - P,Media de crescimento - P,Inflacao aproximada,Erro aproximacao
0,2020T1,2020-01-01,103.665,0.98913,101.453,1.010696,NaN,2.105831,NaN,0.314796,NaN,0.82493,NaN,1.587785,NaN,NaN
1,2020T2,2020-01-01,107.297,0.97758,100.382,1.044922,3.503593,2.105831,-1.167693,0.314796,-1.055661,0.82493,3.386399,1.587785,3.391562,-0.005162
2,2020T3,2020-01-01,111.334,0.95334,100.716,1.053846,3.762454,2.105831,-2.479592,0.314796,0.332729,0.82493,0.853997,1.587785,0.950132,-0.096135
3,2020T4,2020-01-01,115.307,0.94183,101.323,1.071816,3.568542,2.105831,-1.207334,0.314796,0.602685,0.82493,1.705162,1.587785,1.758523,-0.053361
4,2021T1,2021-01-01,117.442,0.94028,102.656,1.075713,1.851579,2.105831,-0.164573,0.314796,1.315595,0.82493,0.363580,1.587785,0.371411,-0.007830

<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Trimestre                 24 non-null     str
 1   Ano                       24 non-null     datetime64[us]
 2   M - oferta monetaria      24 non-null     float64
 3   V - velocidade            24 non-null     float64
 4   Y - produto real          24 non-null     float64
 5   P - nivel de precos       24 non-null     float64
 6   Taxa de crescimento - M   23 non-null     float64
 7   Media de crescimento - M  24 non-null     float64
 8   Taxa de crescimento - V   23 non-null     float64
 9   Media de crescimento - V  24 non-null     float64
 10  Taxa de crescimento - Y   23 non-null     float64
 11  Media de crescimento - Y  24 non-null     float64
 12  Taxa de crescimento - P   23 non-null     float64
 13  Media de crescimento - P  24 non-null     float64
 14  Inflacao aproximada       23 non-null     float64
 15  Erro aproximacao          23 non-null     float64
dtypes: datetime64[us](1), float64(14), str(1)
memory usage: 3.3 KB

['Trimestre',
 'Ano',
 'M - oferta monetaria',
 'V - velocidade',
 'Y - produto real',
 'P - nivel de precos',
 'Taxa de crescimento - M',
 'Media de crescimento - M',
 'Taxa de crescimento - V',
 'Media de crescimento - V',
 'Taxa de crescimento - Y',
 'Media de crescimento - Y',
 'Taxa de crescimento - P',
 'Media de crescimento - P',
 'Inflacao aproximada',
 'Erro aproximacao']

In [4]:
# remover coluna

df.drop(columns=['P - real', 'Inflação aproximada', 'Diferenca - P' ], inplace=True)

list(df.columns)

KeyError: "['P - real', 'Inflação aproximada', 'Diferenca - P'] not found in axis"

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Trimestre                 24 non-null     str
 1   Ano                       24 non-null     datetime64[us]
 2   M - oferta monetaria      24 non-null     float64
 3   V - velocidade            24 non-null     float64
 4   Y - produto real          24 non-null     float64
 5   P - nivel de precos       24 non-null     float64
 6   Taxa de crescimento - M   23 non-null     float64
 7   Media de crescimento - M  24 non-null     float64
 8   Taxa de crescimento - V   23 non-null     float64
 9   Media de crescimento - V  24 non-null     float64
 10  Taxa de crescimento - Y   23 non-null     float64
 11  Media de crescimento - Y  24 non-null     float64
 12  Taxa de crescimento - P   23 non-null     float64
 13  Media de crescimento - P  24 non-null     float64
 14  Inflacao aproximada       23 non-null     float64
 15  Erro aproximacao          23 non-null     float64
dtypes: datetime64[us](1), float64(14), str(1)
memory usage: 3.3 KB

In [6]:
display(df)

# 1. Encontra o índice da linha com o maior valor
maior_inflacao = df['Inflacao aproximada'].idxmax()

# 2. Seleciona a linha desse índice e apenas as colunas
resultado_inflacao = df.loc[[maior_inflacao], ['Trimestre', 'Inflacao aproximada']]

#ou, uma forma mais limpa, usando o nlargest, que retorna com a maior linha

maior_preco = df.nlargest(1,'Taxa de crescimento - P')[['Trimestre', 'Taxa de crescimento - P']]

# seleciona uma unica linha com a media de crescimento.

display(df['Media de crescimento - M'].iloc[0])

media = df['Taxa de crescimento - M'].mean()
display(media)

# comparacao para descobrir periodos em que a velocidade diminuiu

diferenca_velocidade = df['V - velocidade'].diff()

menor_velocidade = df[diferenca_velocidade < 0]

display(menor_velocidade[['Trimestre', 'V - velocidade', 'Taxa de crescimento - V']])



display(maior_preco)
display(resultado_inflacao.style.set_caption("Maior inflação registrada"))

#Qual foi a diferença entre a inflação aproximada e a inflação calculada pela variação de P?

display(df[['Taxa de crescimento - P','Inflacao aproximada', 'Erro aproximacao']])


#O crescimento da oferta monetária foi sempre acompanhado de inflação positiva?

df['Inflacao positiva?'] = np.where(df['Inflacao aproximada'] > 0, 'Sim', 'Não')

df['crescimento m positivo'] = np.where(df['Taxa de crescimento - M'] > 0, 'Sim', 'Não')

#verifica se os resultados correspondem
corresponde_m_i = df['crescimento m positivo'] == df['Inflacao positiva?']

resultado_m_i = df[corresponde_m_i]

display(resultado_m_i[['Trimestre', 'Inflacao positiva?', 'crescimento m positivo', 'Inflacao aproximada', 'Taxa de crescimento - M' ]])

#respondendo a pregunta original

excessoes = df[
    (df['Taxa de crescimento - M'] > 0)
    & (df['Taxa de crescimento - P'] <= 0)
]

display(excessoes[[
    'Trimestre',
    'Taxa de crescimento - M',
    'Taxa de crescimento - P'
    
]])

# display(df['Inflacao positiva?'])

,Trimestre,Ano,M - oferta monetaria,V - velocidade,Y - produto real,P - nivel de precos,Taxa de crescimento - M,Media de crescimento - M,Taxa de crescimento - V,Media de crescimento - V,Taxa de crescimento - Y,Media de crescimento - Y,Taxa de crescimento - P,Media de crescimento - P,Inflacao aproximada,Erro aproximacao
0,2020T1,2020-01-01,103.665,0.98913,101.453,1.010696,NaN,2.105831,NaN,0.314796,NaN,0.82493,NaN,1.587785,NaN,NaN
1,2020T2,2020-01-01,107.297,0.97758,100.382,1.044922,3.503593,2.105831,-1.167693,0.314796,-1.055661,0.82493,3.386399,1.587785,3.391562,-0.005162
2,2020T3,2020-01-01,111.334,0.95334,100.716,1.053846,3.762454,2.105831,-2.479592,0.314796,0.332729,0.82493,0.853997,1.587785,0.950132,-0.096135
3,2020T4,2020-01-01,115.307,0.94183,101.323,1.071816,3.568542,2.105831,-1.207334,0.314796,0.602685,0.82493,1.705162,1.587785,1.758523,-0.053361
4,2021T1,2021-01-01,117.442,0.94028,102.656,1.075713,1.851579,2.105831,-0.164573,0.314796,1.315595,0.82493,0.363580,1.587785,0.371411,-0.007830
5,2021T2,2021-01-01,119.981,0.94031,104.194,1.082781,2.161918,2.105831,0.003191,0.314796,1.498208,0.82493,0.657125,1.587785,0.666901,-0.009776
6,2021T3,2021-01-01,121.833,0.94807,105.601,1.093798,1.543578,2.105831,0.825260,0.314796,1.350366,0.82493,1.017471,1.587785,1.018472,-0.001001
7,2021T4,2021-01-01,123.789,0.95386,106.626,1.107398,1.605476,2.105831,0.610714,0.314796,0.970635,0.82493,1.243293,1.587785,1.245556,-0.002263
8,2022T1,2022-01-01,126.473,0.95405,107.637,1.121005,2.168206,2.105831,0.019919,0.314796,0.948174,0.82493,1.228732,1.587785,1.239951,-0.011219
9,2022T2,2022-01-01,129.152,0.96242,108.359,1.147099,2.118239,2.105831,0.877313,0.314796,0.670773,0.82493,2.327748,1.587785,2.324778,0.002970
10,2022T3,2022-01-01,131.163,0.97666,109.301,1.172008,1.557080,2.105831,1.479603,0.314796,0.869332,0.82493,2.171512,1.587785,2.167351,0.004161
11,2022T4,2022-01-01,134.045,0.97552,110.694,1.181307,2.197266,2.105831,-0.116724,0.314796,1.274462,0.82493,0.793403,1.587785,0.806079,-0.012676
12,2023T1,2023-01-01,136.819,0.98957,111.050,1.219198,2.069454,2.105831,1.440258,0.314796,0.321607,0.82493,3.207594,1.587785,3.188104,0.019490
13,2023T2,2023-01-01,139.228,0.98663,112.385,1.222285,1.760720,2.105831,-0.297099,0.314796,1.202161,0.82493,0.253186,1.587785,0.261460,-0.008275
14,2023T3,2023-01-01,141.662,1.00162,113.228,1.253148,1.748212,2.105831,1.519313,0.314796,0.750100,0.82493,2.525045,1.587785,2.517425,0.007620
15,2023T4,2023-01-01,144.555,1.01500,113.892,1.288267,2.042185,2.105831,1.335836,0.314796,0.586427,0.82493,2.802439,1.587785,2.791593,0.010846
16,2024T1,2024-01-01,147.286,1.03037,114.954,1.320172,1.889246,2.105831,1.514286,0.314796,0.932462,0.82493,2.476585,1.587785,2.471070,0.005515
17,2024T2,2024-01-01,149.867,1.03176,116.384,1.328591,1.752373,2.105831,0.134903,0.314796,1.243976,0.82493,0.637731,1.587785,0.643300,-0.005569
18,2024T3,2024-01-01,152.317,1.04009,117.509,1.348181,1.634783,2.105831,0.807358,0.314796,0.966628,0.82493,1.474459,1.587785,1.475513,-0.001054
19,2024T4,2024-01-01,155.192,1.03863,118.790,1.356908,1.887511,2.105831,-0.140372,0.314796,1.090129,0.82493,0.647303,1.587785,0.657009,-0.009706
20,2025T1,2025-01-01,158.515,1.04110,119.619,1.379630,2.141219,2.105831,0.237813,0.314796,0.697870,0.82493,1.674567,1.587785,1.681162,-0.006594
21,2025T2,2025-01-01,161.902,1.04897,120.370,1.410903,2.136706,2.105831,0.755931,0.314796,0.627827,0.82493,2.266732,1.587785,2.264811,0.001921
22,2025T3,2025-01-01,164.341,1.06058,121.233,1.437701,1.506467,2.105831,1.106800,0.314796,0.716956,0.82493,1.899367,1.587785,1.896311,0.003056
23,2025T4,2025-01-01,167.344,1.06212,122.518,1.450721,1.827298,2.105831,0.145204,0.314796,1.059942,0.82493,0.905614,1.587785,0.912559,-0.006946

np.float64(2.1058306099836854)

np.float64(2.1058306099836854)

   Trimestre  V - velocidade  Taxa de crescimento - V
1     2020T2         0.97758                -1.167693
2     2020T3         0.95334                -2.479592
3     2020T4         0.94183                -1.207334
4     2021T1         0.94028                -0.164573
11    2022T4         0.97552                -0.116724
13    2023T2         0.98663                -0.297099
19    2024T4         1.03863                -0.140372

  Trimestre  Taxa de crescimento - P
1    2020T2                 3.386399

    Taxa de crescimento - P  Inflacao aproximada  Erro aproximacao
0                       NaN                  NaN               NaN
1                  3.386399             3.391562         -0.005162
2                  0.853997             0.950132         -0.096135
3                  1.705162             1.758523         -0.053361
4                  0.363580             0.371411         -0.007830
5                  0.657125             0.666901         -0.009776
6                  1.017471             1.018472         -0.001001
7                  1.243293             1.245556         -0.002263
8                  1.228732             1.239951         -0.011219
9                  2.327748             2.324778          0.002970
10                 2.171512             2.167351          0.004161
11                 0.793403             0.806079         -0.012676
12                 3.207594             3.188104          0.019490
13                 0.253186             0.261460         -0.008275
14                 2.525045             2.517425          0.007620
15                 2.802439             2.791593          0.010846
16                 2.476585             2.471070          0.005515
17                 0.637731             0.643300         -0.005569
18                 1.474459             1.475513         -0.001054
19                 0.647303             0.657009         -0.009706
20                 1.674567             1.681162         -0.006594
21                 2.266732             2.264811          0.001921
22                 1.899367             1.896311          0.003056
23                 0.905614             0.912559         -0.006946

,Trimestre,Inflacao positiva?,crescimento m positivo,Inflacao aproximada,Taxa de crescimento - M
0,2020T1,Não,Não,NaN,NaN
1,2020T2,Sim,Sim,3.391562,3.503593
2,2020T3,Sim,Sim,0.950132,3.762454
3,2020T4,Sim,Sim,1.758523,3.568542
4,2021T1,Sim,Sim,0.371411,1.851579
5,2021T2,Sim,Sim,0.666901,2.161918
6,2021T3,Sim,Sim,1.018472,1.543578
7,2021T4,Sim,Sim,1.245556,1.605476
8,2022T1,Sim,Sim,1.239951,2.168206
9,2022T2,Sim,Sim,2.324778,2.118239
10,2022T3,Sim,Sim,2.167351,1.557080
11,2022T4,Sim,Sim,0.806079,2.197266
12,2023T1,Sim,Sim,3.188104,2.069454
13,2023T2,Sim,Sim,0.261460,1.760720
14,2023T3,Sim,Sim,2.517425,1.748212
15,2023T4,Sim,Sim,2.791593,2.042185
16,2024T1,Sim,Sim,2.471070,1.889246
17,2024T2,Sim,Sim,0.643300,1.752373
18,2024T3,Sim,Sim,1.475513,1.634783
19,2024T4,Sim,Sim,0.657009,1.887511
20,2025T1,Sim,Sim,1.681162,2.141219
21,2025T2,Sim,Sim,2.264811,2.136706
22,2025T3,Sim,Sim,1.896311,1.506467
23,2025T4,Sim,Sim,0.912559,1.827298

Empty DataFrame
Columns: [Trimestre, Taxa de crescimento - M, Taxa de crescimento - P]
Index: []

In [7]:
# df['Ano'] = df['Ano'].astype('int64')

df_ano = pd.read_excel('dados/economi.xlsx')
df['Ano'] = df_ano['Ano']

df.info()

df.head()

display(df[['Taxa de crescimento - M', 'Taxa de crescimento - V', 'Taxa de crescimento - Y', 'Taxa de crescimento - P']].head())

inflacao_media = df.groupby('Ano')['Taxa de crescimento - P'].mean()
oferta_m = df.groupby('Ano')['Taxa de crescimento - M'].agg(
    ['mean', 'min', 'max']
)
maior_inflacao = inflacao_media.idxmax()

display(inflacao_media)
display(oferta_m)
display(maior_inflacao)

<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Trimestre                 24 non-null     str
 1   Ano                       24 non-null     int64
 2   M - oferta monetaria      24 non-null     float64
 3   V - velocidade            24 non-null     float64
 4   Y - produto real          24 non-null     float64
 5   P - nivel de precos       24 non-null     float64
 6   Taxa de crescimento - M   23 non-null     float64
 7   Media de crescimento - M  24 non-null     float64
 8   Taxa de crescimento - V   23 non-null     float64
 9   Media de crescimento - V  24 non-null     float64
 10  Taxa de crescimento - Y   23 non-null     float64
 11  Media de crescimento - Y  24 non-null     float64
 12  Taxa de crescimento - P   23 non-null     float64
 13  Media de crescimento - P  24 non-null     float64
 14  Inflacao aproximada       23 non-null     float64
 15  Erro aproximacao          23 non-null     float64
 16  Inflacao positiva?        24 non-null     str
 17  crescimento m positivo    24 non-null     str
dtypes: float64(14), int64(1), str(3)
memory usage: 3.8 KB

,Taxa de crescimento - M,Taxa de crescimento - V,Taxa de crescimento - Y,Taxa de crescimento - P
0,NaN,NaN,NaN,NaN
1,3.503593,-1.167693,-1.055661,3.386399
2,3.762454,-2.479592,0.332729,0.853997
3,3.568542,-1.207334,0.602685,1.705162
4,1.851579,-0.164573,1.315595,0.363580

Ano
2020    1.981853
2021    0.820367
2022    1.630349
2023    2.197066
2024    1.309020
2025    1.686570
Name: Taxa de crescimento - P, dtype: float64

          mean       min       max
Ano
2020  3.611530  3.503593  3.762454
2021  1.790638  1.543578  2.161918
2022  2.010198  1.557080  2.197266
2023  1.905143  1.748212  2.069454
2024  1.790978  1.634783  1.889246
2025  1.902922  1.506467  2.141219

np.int64(2023)

In [8]:
consolidando_gb = df.groupby('Ano')[['Taxa de crescimento - M', 'Taxa de crescimento - V', 'Taxa de crescimento - Y', 'Taxa de crescimento - P']].mean()

display(consolidando_gb)

df.head()

,Taxa de crescimento - M,Taxa de crescimento - V,Taxa de crescimento - Y,Taxa de crescimento - P
Ano,,,,
2020,3.611530,-1.618206,-0.040082,1.981853
2021,1.790638,0.318648,1.283701,0.820367
2022,2.010198,0.565028,0.940685,1.630349
2023,1.905143,0.999577,0.715074,2.197066
2024,1.790978,0.579044,1.058299,1.309020
2025,1.902922,0.561437,0.775649,1.686570

,Trimestre,Ano,M - oferta monetaria,V - velocidade,Y - produto real,P - nivel de precos,Taxa de crescimento - M,Media de crescimento - M,Taxa de crescimento - V,Media de crescimento - V,Taxa de crescimento - Y,Media de crescimento - Y,Taxa de crescimento - P,Media de crescimento - P,Inflacao aproximada,Erro aproximacao,Inflacao positiva?,crescimento m positivo
0,2020T1,2020,103.665,0.98913,101.453,1.010696,NaN,2.105831,NaN,0.314796,NaN,0.82493,NaN,1.587785,NaN,NaN,Não,Não
1,2020T2,2020,107.297,0.97758,100.382,1.044922,3.503593,2.105831,-1.167693,0.314796,-1.055661,0.82493,3.386399,1.587785,3.391562,-0.005162,Sim,Sim
2,2020T3,2020,111.334,0.95334,100.716,1.053846,3.762454,2.105831,-2.479592,0.314796,0.332729,0.82493,0.853997,1.587785,0.950132,-0.096135,Sim,Sim
3,2020T4,2020,115.307,0.94183,101.323,1.071816,3.568542,2.105831,-1.207334,0.314796,0.602685,0.82493,1.705162,1.587785,1.758523,-0.053361,Sim,Sim
4,2021T1,2021,117.442,0.94028,102.656,1.075713,1.851579,2.105831,-0.164573,0.314796,1.315595,0.82493,0.363580,1.587785,0.371411,-0.007830,Sim,Sim